server {
    listen 80;
    root /var/www/html;
    index index.php index.html;

    location / {
        proxy_pass http://apache:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
